# Generated by Django 2.1.2 on 2018-12-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Gigs',
        ),
    ]
