# Generated by Django 2.1.2 on 2018-12-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_auto_20181205_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigs',
            name='body',
        ),
        migrations.RemoveField(
            model_name='gigs',
            name='title',
        ),
        migrations.AddField(
            model_name='gigs',
            name='location',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='gigs',
            name='venue',
            field=models.CharField(default='', max_length=140),
        ),
    ]
