# Generated by Django 2.1.2 on 2018-12-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_auto_20181205_1802'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gigs',
            new_name='Gig',
        ),
    ]
